### ISSUE TITLE
example fails

### ISSUE THREAD

**Issue by yzsatgithub** [wwliao/bkheatmap#2]
When running your code in README file, the following error popped out:

```
>>> bkheatmap(df, prefix=prefix, scale="column")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/bkheatmap.py", line 137, in bkheatmap
    toolbar_location=None, webgl=True)
  File "/usr/local/lib/python2.7/dist-packages/bokeh/plotting/figure.py", line 793, in figure
    return Figure(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bokeh/plotting/figure.py", line 138, in __init__
    super(Figure, self).__init__(*arg, **kw)
  File "/usr/local/lib/python2.7/dist-packages/bokeh/models/plots.py", line 49, in __init__
    super(LayoutDOM, self).__init__(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bokeh/model.py", line 219, in __init__
    super(Model, self).__init__(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bokeh/core/has_props.py", line 236, in __init__
    setattr(self, name, value)
  File "/usr/local/lib/python2.7/dist-packages/bokeh/core/has_props.py", line 271, in __setattr__
    (name, self.__class__.__name__, text, nice_join(matches)))
AttributeError: unexpected attribute 'webgl' to Figure, possible attributes are above, aspect_scale, background_fill_alpha, background_fill_color, below, border_fill_alpha, border_fill_color, css_classes, disabled, extra_x_ranges, extra_y_ranges, h_symmetry, height, hidpi, inner_height, inner_width, js_event_callbacks, js_property_callbacks, layout_height, layout_width, left, lod_factor, lod_interval, lod_threshold, lod_timeout, match_aspect, min_border, min_border_bottom, min_border_left, min_border_right, min_border_top, name, outline_line_alpha, outline_line_cap, outline_line_color, outline_line_dash, outline_line_dash_offset, outline_line_join, outline_line_width, output_backend, plot_height, plot_width, renderers, right, sizing_mode, subscribed_events, tags, title, title_location, toolbar, toolbar_location, toolbar_sticky, v_symmetry, width, x_range, x_scale, y_range or y_scale
```

I think this has something to do with package dependencies. Do you have any idea? Thank you

**Comment by wwliao** [comment]
Bokeh is in active development and a lot of things keep changing. I used Bokeh v0.12.2 when I developed this tool. I think it still works if you install the same version (v0.12.2).
